### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by hylx01** [Flippy0-ops/VytrixDuperV3#4]
its a virus dont even bother downloading

**Comment by Flippy0-ops** [comment]
Sorry, but what? I spent two whole weeks developing this tool, and you're out here calling it a virus... You need to think before speaking because this really pisses me off. If you're jealous, just don't use it.

**Comment by kianb234** [comment]
100% a virus glad others found out too

**Comment by kianb234** [comment]
> Sorry, but what? I spent two whole weeks developing this tool, and you're out here calling it a virus... You need to think before speaking because this really pisses me off. If you're jealous, just don't use it.

nobody is jealous of your token logging, camera opening threat tool

**Comment by Flippy0-ops** [comment]
nope
