### ISSUE TITLE
dont use this shit 

### ISSUE THREAD

**Issue by iHKPlays** [Flippy0-ops/VytrixDuperV3#6]
i looked at the source and deadass laughed out loud bro, its just sleeping and printing its not actually doing anything

**Comment by Flippy0-ops** [comment]
What's Ur khord lil bro I can prove it by opening it lmao

**Comment by Flippy0-ops** [comment]
U don't know nun about sources

**Comment by Flippy0-ops** [comment]
Hurry the fuck up B4 I close this issue

**Comment by iHKPlays** [comment]
![image](https://github.com/Flippy0-ops/VytrixDuperV3/assets/85902091/64d74a4a-3c4e-4f67-bc94-4add489fa93d)
.hkplays add me dumbass, ur literally doing nothing and makin git seem like you're an epic hackerman that is breaching servers or some shit

**Comment by Flippy0-ops** [comment]
Are u absolutely mental??!! That isn't even the source code... It's the batch file click on the source code dumbass

**Comment by Flippy0-ops** [comment]
It's real and I have proven it
If u don't believe me you can officially call urself a retard
